### ISSUE TITLE
不知道如何讓 紅色的線根據文章內容多寡伸縮

### ISSUE THREAD

**Issue by AlvinWang627** [a2623212/project-simple-twitter-vue#17]
![image](https://user-images.githubusercontent.com/93432312/155746419-368d668e-e001-4ad3-9d6c-f918450adcf1.png)

**Comment by a2623212** [comment]
的確不簡單，我也來找一下有沒有相關作法

**Comment by AlvinWang627** [comment]
這個先放著，之後再研究，重要性低
